### ISSUE TITLE
【Bug】In the template: "excelTemplate.set("students", students);" If you set more than one, the table will be confused.

### ISSUE THREAD

**Issue by geniyangge** [plantain-00/js-excel-template#11]
Just like:
![image](https://github.com/plantain-00/js-excel-template/assets/119825994/5adcad64-2557-493e-a396-cf50e74d63ad)
```
const student1 = [
  { name: 'Tommy', age: 12 },
  { name: 'Philips', age: 13 },
  { name: 'Sara', age: 14 },
];
const student2 = [
  { name: 'Jack', age: 15 },
  { name: 'Yun', age: 16 },
  { name: 'Anna', age: 17 },
];

excelTemplate.set('student1', student1);
excelTemplate.set('student2', student2);
```
![image](https://github.com/plantain-00/js-excel-template/assets/119825994/cec79796-02bf-4634-92af-a697603fb23e)

**Comment by plantain-00** [comment]
This tool does not support your case, because it duplicates rows for array items.
You may merge them like:

```js
const student1 = [
  { name: 'Tommy', age: 12, name2: 'Jack', age2: '' },
  { name: 'Philips', age: 13, name2: 'Yun', age2: 16 },
  { name: 'Sara', age: 14, name2: '', age2: '' },
];
excelTemplate.set('student1', student1);
```

**Comment by plantain-00** [comment]
This tool does not support your case, because it duplicates rows for array items.
You may merge them like:

```js
const student1 = [
  { name: 'Tommy', age: 12, name2: 'Jack', age2: '' },
  { name: 'Philips', age: 13, name2: 'Yun', age2: 16 },
  { name: 'Sara', age: 14, name2: '', age2: '' },
];
excelTemplate.set('student1', student1);
```

**Comment by geniyangge** [comment]
Well, thank you.
If possible, I hope the next version can support this way of writing. After all, this way of writing is more suitable!

**Comment by faheemhameed** [comment]
This is a cool package. I wanted this to be improved further. I used TinyButStrong (https://www.tinybutstrong.com/) in my legacy PHP application for a similar purpose and it worked very well.

Now I needed something similar for my nodejs app and your package looks good. However it can be further improved.
