### ISSUE TITLE
Cant find source or code for browser version

### ISSUE THREAD

**Issue by FullBringEc** [plantain-00/js-excel-template#8]
Cant find source or code for browser version :(

**Comment by plantain-00** [comment]
![屏幕快照 2023-01-09 08 01 06](https://user-images.githubusercontent.com/7639395/211225480-ebac819b-8028-4355-a33a-3b0f83c9a440.png)
There is browser version code in npm v3.0.2 package.

**Comment by FullBringEc** [comment]
Thanks I already found it but I cant use it, I'm not used to NPM, I thought it was like any other normal javascript plugin, my fault. I will do some research.

Uncaught SyntaxError: Cannot use import statement outside a module

**Comment by FullBringEc** [comment]
If I use type="modules" I get this error

Uncaught TypeError: Failed to resolve module specifier "tslib". Relative references must start with either "/", "./", or "../".

This are my lines:

    <script src="src/FileSaver.js"></script>
    <script src="src/exceljs.min.js"></script>
    <script src="src/js-excel-template.js"></script>
    <script type="module" src="src/browser.js"></script>

**Comment by plantain-00** [comment]
If you use it with `script` tag, you should use this file:
![屏幕快照 2023-01-10 07 24 56](https://user-images.githubusercontent.com/7639395/211428331-ddf50880-cd4a-4db2-9f2c-41274407e1fc.png)

**Comment by plantain-00** [comment]
I updated the document:
![屏幕快照 2023-01-10 07 30 01](https://user-images.githubusercontent.com/7639395/211428783-85358344-5aeb-4fe3-957c-50b462f00640.png)

**Comment by FullBringEc** [comment]
Thanks, Issue is now solved.
