### ISSUE TITLE
template placeholder not getting replaced

### ISSUE THREAD

**Issue by Sa1To-Bob** [plantain-00/js-excel-template#9]
#### Environment(if relevant):Browser

Hi, 
frist, thx a for this project. 
I was testing this excel template module, but I can not get any changes in my template:

Placeholder {MyVariable} get untuched und browser give back my template file.

I tried it with varables and also hard coded values like in your exaples:
excelTemplate.set("name", "John");
no error at  all... Excel get loaded and saved without changes.

**Comment by plantain-00** [comment]
I cannot reproduce your issue.
This package works with the sample excel file(https://github.com/plantain-00/js-excel-template/blob/master/demo/test.xlsx ) and can be used like https://github.com/plantain-00/js-excel-template/blob/master/demo/index.ts

**Comment by Sa1To-Bob** [comment]
You are right, stand a lone is working well. 
I tested it in a vue2 project with some other stuff, maybe there are some independence glitches. 
sorry to waste your time... if I get the problem on my side I'll let you know if there is interest.

**Comment by Sa1To-Bob** [comment]
I got it, for browser module import it seem I needed add also exceljs... 
import * as FileSaver from "file-saver";
import "exceljs/dist/exceljs.min.js"
import JsExcelTemplate from "js-excel-template/js-excel-template.min.js";
